### ISSUE TITLE
Not possible to specify floating IP subnet when creating kubernikus cluster

### ISSUE THREAD

**Issue by zoltan-keller** [sapcc/terraform-provider-ccloud#43]
Hi there,

when creating a kubernikus cluster in ccloud there is no option to specify the subnet for the external network from which the floating IP of a loadbalancer will be assigned. There is an argument for the openstack block called lB_subnet_id, but this specifies the subnet of the private network. Because of this missing option when the external network has several subnets the floating IP will be assigned from one of these subnets randomly.

### Terraform Version
Terraform v0.11.13
+ provider.ccloud v1.4.7
+ provider.environment v1.0.0
+ provider.external v1.1.2
+ provider.helm v0.10.2
+ provider.kubernetes v1.7.0
+ provider.openstack v1.18.0

### Affected Resource(s)
ccloud_kubernetes_v1

### Expected Behavior
When a loadbalancer is created for a kubernetes service the floating IP is taken from the specified subnet of the external network.

### Actual Behavior
Loadbalancer is created with a floating IP taken from a random subnet of the external network

### Steps to Reproduce
`terraform apply`

### References
https://github.com/sapcc/kubernikus/issues/434

**Comment by kayrus** [comment]
You can try to annotate a service following this doc: https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/expose-applications-using-loadbalancer-type-service.md#switching-between-floating-subnets-by-using-preconfigured-classes
Officially you have to configure CCM, which is not possible in kubernikus, but give it a try and let me know if it works for you.
