### ISSUE TITLE
Compatibility with TF 0.13

### ISSUE THREAD

**Issue by UncleIS** [sapcc/terraform-provider-ccloud#46]
Hello, colleagues. 

I'd like to ask if the current implementation of the provider is compatible with TF 0.13? 

As far as I understand, the new version of Terraform is able to download and install providers directly from GitHub, and it would be great if that feature would be supported by `ccloud` provider as well.

Thanks!

**Comment by kayrus** [comment]
@UncleIS ccloud provider is compatible with terraform 0.13. The only thing you need to know that a new path for storing provider binaries has been changed. We tested that the following paths to the binary should work fine with terraform 0.13:
* Linux: `~/.terraform.d/plugins/registry.terraform.io/terraform-providers/ccloud/1.4.7/linux_amd64/terraform-provider-ccloud_v1.4.7_x4`
* Darwin `~/.terraform.d/plugins/registry.terraform.io/terraform-providers/ccloud/1.4.7/darwin_amd64/terraform-provider-ccloud_v1.4.7_x4`
* Windows `~/.terraform.d/plugins/registry.terraform.io/terraform-providers/ccloud/1.4.7/windows_amd64/terraform-provider-ccloud_v1.4.7_x4`

The following definition must exist in the terraform script:

```hcl
terraform {
  required_providers {
    openstack = {
      source = "terraform-providers/openstack"
    }
    ccloud = {
      source = "terraform-providers/ccloud"
    }
  }
}
```

**Comment by kayrus** [comment]
CCloud EE provider is now accessible via Terraform Registry. You can refer to it using the code below:

```hcl
terraform {
  required_providers {
    ccloud = {
      source = "sapcc/ccloud"
    }
  }
}
```
