### ISSUE TITLE
Add support for CCloud automation management

### ISSUE THREAD

**Issue by UncleIS** [sapcc/terraform-provider-ccloud#5]
Hello, colleagues. 

This is a feature request to introduce support for automation management in CCloud with Terraform: it is desired to:

- Add instances to automation at the time of instance creation;
- Manage automations (create / modify / delete) 

Thanks!

**Comment by kayrus** [comment]
This could be done by specifying the [user-data](https://www.terraform.io/docs/providers/openstack/r/compute_instance_v2.html#user_data) field

**Comment by UncleIS** [comment]
Could you provide an example of what exactly needs to be provided there?

Thanks!

**Comment by kayrus** [comment]
I thought, that adding an instance into the arc automation list doesn't require addition API calls, but it is not true. However a new resource is not mandatory. Adding instance into the automation could be done by API hooks. API calls should be clarified though.
