### ISSUE TITLE
Remove few attributes for arc agent resource

### ISSUE THREAD

**Issue by ashkraba** [sapcc/terraform-provider-ccloud#50]
Good day colleagues,

Is it possible to remove few attributes for arc agent resource https://github.com/sapcc/terraform-provider-ccloud/blob/master/ccloud/data_source_ccloud_arc_agent_v1.go#L83-L91 ?

The reason: In terraform v.1 the output of terraform plan command was changed and now it shows not only resources which will be changed but and resources that were changed outside the terraform. It is great behaviour and helps to work with drifts. But now we have some computed attributes for arc agent resource that predictably changes from time to time outside the terraform automatically and as a result, we have information about it in every terraform plan output. It creates excessive noise in the plan command output. 
```# ccloud_arc_agent_v1.app has been changed
  ~ resource "ccloud_arc_agent_v1" "app" {
      ~ updated_at   = "2021-09-14T10:01:18Z" -> "2021-09-21T11:07:18Z"
      ~ updated_with = "6ca72b40-debe-4ea5-95d3-6d6bd473d0cb" -> "bf261711-e333-40ab-848d-dc66c03bff9d"
```

The only way to prevent seeing those changes would be for the provider to not report them in response to refreshing. Terraform reports any change that the provider reports, and so it’s the generally provider’s responsibility to only report useful information which is relevant to the settings being managed by Terraform.

Due to those two attributes constantly change even though you’re not changing anything about the infrastructure with Terraform then it seems like there’s little value in the provider actually tracking them, and so we could drop those attributes altogether in a future release, in order to reduce the noise and focus the change reports only on data that’s actually relevant to the task of managing these objects with Terraform.

Could you please drop it in the new release or should we build it ourself without these attributes?

Thanks a lot in advance and Regards,
Aleksandr

**Comment by kayrus** [comment]
these are computed attributes and when they're changed, recent terraform versions warn you about this.

**Comment by kayrus** [comment]
@ashkraba since we haven't received any updates for a while, I'm closing this issue
