### ISSUE TITLE
Add support for shared filesystem management

### ISSUE THREAD

**Issue by UncleIS** [sapcc/terraform-provider-ccloud#6]
Hello, colleagues. 

I'd like to request a shared filesystem storage support, so that one could create and manage NFS shares via Terraform. 

Thanks!

**Comment by kayrus** [comment]
It will be [released](https://github.com/terraform-providers/terraform-provider-openstack/blob/6a699403eee0b19e5ffa9feab9a1de6be39d47fe/CHANGELOG.md#1140-unreleased) in official Openstack terraform provider soon.

**Comment by kayrus** [comment]
Released:
- https://www.terraform.io/docs/providers/openstack/r/sharedfilesystem_securityservice_v2.html
- https://www.terraform.io/docs/providers/openstack/r/sharedfilesystem_sharenetwork_v2.html
- https://www.terraform.io/docs/providers/openstack/r/sharedfilesystem_share_v2.html
- https://www.terraform.io/docs/providers/openstack/r/sharedfilesystem_share_access_v2.html

Data sources:
- https://www.terraform.io/docs/providers/openstack/d/sharedfilesystem_share_v2.html
- https://www.terraform.io/docs/providers/openstack/d/sharedfilesystem_sharenetwork_v2.html
- https://www.terraform.io/docs/providers/openstack/d/sharedfilesystem_snapshot_v2.html

**Comment by UncleIS** [comment]
Great, thanks!
