### ISSUE TITLE
ccloud_billing_project_masterdata update

### ISSUE THREAD

**Issue by ashkraba** [sapcc/terraform-provider-ccloud#65]
Good day, colleagues.

Looks like the  ccloud_billing_project_masterdata resource has been changed and now it contains new mandatory parameters - Asset Owner (Primary Contact), Run Team (Operator),  Inventory Role, and Project info. Could you please update it in the provider?

Thanks a lot in advance.

**Comment by ashkraba** [comment]
Hello,

Thanks for the updates. Now it works, but when it tries to update masterdata we are getting the next error
`Error getting billing project masterdata: Request forbidden: [GET https://billing.eu-de-2.cloud.sap:64000/masterdata/projects], error message: {"Error":{"status":403,"message":"Only project-admins are allowed to get the costobject for a project!"}}`
As you could see the project ID is missed in the request. If I understand correctly it should be https://billing.eu-de-2.cloud.sap:64000/masterdata/projects/ID_OF THE_PROJECT

Thanks a lot in advance.

**Comment by kayrus** [comment]
As a workaround please define the `project_id`. I'll try to fix the `project_id` autodetect logic in the next release.
