### ISSUE TITLE
Add support for Kubernikus multi-availability-zones feature

### ISSUE THREAD

**Issue by UncleIS** [sapcc/terraform-provider-ccloud#8]
Hello, colleagues. 

It would be nice to add the support of mutli-availability-zones feature that Kubernikus received recently.

My assumption is that the feature should go somewhere here: https://github.com/sapcc/terraform-provider-ccloud/blob/bb77032a269b97fb97b0464f6036aa2d8b225083/ccloud/resource_ccloud_kubernetes.go#L86-L113

Thanks!

**Comment by BugRoger** [comment]
Your wish is my command! 😄 You can give it a whirl. Take note that changing an AVZ via Terraform forces a recreation of the whole cluster. 

Implemented with PR #9.
